# Generated by Django 4.2 on 2023-04-28 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rest_app", "0002_studentmodel"),
    ]

    operations = [
        migrations.DeleteModel(name="StudentModel",),
    ]
