# Generated by Django 4.2 on 2023-05-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_app", "0003_delete_studentmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("phone", models.IntegerField()),
            ],
        ),
    ]
