# Generated by Django 4.2 on 2023-05-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_app", "0004_personmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("salary", models.IntegerField()),
                ("department", models.CharField(max_length=50)),
                ("designation", models.CharField(max_length=50)),
                ("company", models.CharField(max_length=50)),
            ],
        ),
    ]
