# Generated by Django 4.2 on 2023-05-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_app", "0005_employeemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_name", models.CharField(max_length=50)),
                ("no_of_seats", models.IntegerField()),
                ("theatre_name", models.CharField(max_length=50)),
                ("rating", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(name="EmployeeModel",),
    ]
