# Generated by Django 4.2 on 2023-05-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_app", "0006_moviemodel_delete_employeemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_name", models.CharField(max_length=50)),
                ("isbn_no", models.IntegerField()),
                ("author", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=50)),
            ],
        ),
    ]
