# Generated by Django 4.2 on 2023-05-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_app", "0008_companymodel_delete_bookmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companymodel",
            name="address",
            field=models.CharField(max_length=100),
        ),
    ]
